name: Driving In America
favicon: null
layout_spectrum: 0.8207230533007532
typography_spectrum: 0.39731932315044105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6953309720847756
  lightness: 0.8687985194846988
  saturation: 0.4690970603842288
  rhythmicContrast: 0.8540704227052629
purpose: []
